<div class="contact-form">
<h2 class="text-center contact-banner-img">Contact Us</h2>
<p class="businessup_block_p">Use the form below and we’ll contact you as soon as possible!</p>
<div class="container">
<div class="row">
	<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
	<div class="col-sm-12">
		<!-- <div class="signup_text">			
			<p>Interested in working with freeboxes? We want to hear from you. Contact us by filling out the form below and we’ll 
get back to you right away!</p>
		</div> -->
		<div class="panel panel-default">
			<div class="panel-heading heading">
				<div class="pull-left"></div>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12">
						<div class="col-md-6">
							<div class="form-group">
								<label>First Name</label>
								<div class="select_group">
									<input class="form-control" type="text" name="firstname" data-validate="{required:true}"/>
								</div>
							</div>
						</div>

						<div class="col-md-6 r-side">
							<div class="form-group">
								<label>Last Name</label>
								<div class="select_group">
									<input class="form-control" type="text" name="lastname" data-validate="{required:true}"/>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="col-md-6">
							<div class="form-group">
								<label>Email </label>
								<div class="select_group">
									<input class="form-control required-entry" name="email" type="email" data-validate="{required:true}"/>
								</div>
							</div>
						</div>
						<div class="col-md-6 r-side">
							<div class="form-group">
								<div class="phone_text">Phone Number</div>
								<div class="select_group">
									<input class="form-control validate-phoneStrictCustom" name="phonenumber" type="text"/>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="col-md-6">
							<div class="form-group">
								<label>Customer Or Business</label>
								<div class="select_group" data-validate="{required:true}">
									<select class="selectpicker validate-select" name="cust-or-business" id="cust-or-business">
										<option value="">Make a selection</option>
										<option value="Customer" data-value="0">Customer</option>
										<option value="Business" data-value="1">Business</option>
										<option value="Other" data-value="2">Other</option>
									</select>
								</div>
							</div>
						</div>
						<div class="col-md-6 r-side">
							<div class="form-group">
								<div class="phone_text">Business Name</div>
								<div class="select_group">
									<input class="form-control" type="text" name="businessname" />
								</div>
							</div>
						</div>
					</div>
				</div>
					
					
					
				
				<div class="col-sm-12">
					<div class="form-group">
						<label>Reason for Contact</label>
						<div class="select_group">
							<select class="selectpicker validate-select" name="reason" data-validate="{required:true}">
								<option value="">Make a selection</option>
								<option value="General Questions">General Questions</option>
								<option value="Customer Orders">Customer Orders</option>
								<option value="Business Orders">Business Orders</option>
								<option value="Pricing">Pricing</option>
								<option value="Other">Other</option>
							</select>
						</div>
					</div>
				</div>
				<!-- <div class="col-md-6">
					<div class="form-group">
						<label>Urgency Level</label>
						<div class="select_group">
							<select class="selectpicker" name="urgency">
								<option value="0">Make a selection</option>
								<option value="Everything's cool, I just want to chat">Everything's cool, I just want to chat</option>
								<option value="I'm alright, but need to speak to someone soon">I'm alright, but need to speak to someone soon</option>
								<option value="Freaking the fuck out, call me ASAP">Freaking the fuck out, call me ASAP</option>
							</select>
						</div>
					</div>
				</div> -->
				<div class="col-sm-12">
					<div class="form-group">
						<label>Message</label>
						<div class="select_group">
							<textarea class="form-control" name="message" data-validate="{required:true}"></textarea>
						</div>
					</div>
				</div>
				
			</div>
		</div>
		<div class="col-sm-12 terms-newsletter">
					
					<div class="form-group">
						<input type="checkbox" name="is_subscribed" checked="checked" value="1" id="is_subscribed" class="checkbox-custom checkbox" autocomplete="off">
						<label class="checkbox-custom-label optional" for="is_subscribed"> Yes, I want to join your mailing list to receive FREE coupons and updates</label>
					</div>
				</div>
	</div>
	
	<div class="message" style="display: inline-block;">
	</div>
	<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit Request') ?>" class="btn btn-border">
    	<span><?php /* @escapeNotVerified */ echo __('Submit Request') ?></span>
    </button>
</form>
</div>
</div>
</div>
<script type="text/javascript">
	require(['jquery', 'jquery/ui'], function($){ 
    	$(document).ready(function()
    	{
    		/*$("#cust-or-business").on('change',function()
    		{
    			$(".b-name").remove();
    			var option = $('option:selected', this).attr('data-value');
    			if(option == 1)
    			{
					$(".r-side").append('<div class="form-group b-name"><div class="phone_text" >Business Name</div><div class="select_group"><input class="form-control" type="text" name="business-name"/></div></div>');
				}
    		});*/
    		$("#contact-form").submit(function()
    		{	
    			if ($(this).valid()) {
	    			var ajax_url = $(this).attr('action');
	    			var ajax_data = $(this).serialize();
	    			$('#contact-form .btn').attr('disabled','disabled');
	    			$('#contact-form .btn').prepend("<i class='fa fa-spinner fa-spin fa-pulse'></i>");
	    			$.ajax(
	    			{
	    				url: ajax_url,
	    				data: ajax_data,
	    				type: 'POST',
	    				datatype: 'json',
	    				success:function(d)
	    				{
	    					$("#contact-form")[0].reset();
	    					$(".message .alert").remove();
	    					$('#contact-form .btn').removeAttr('disabled');
	    					$('#contact-form .btn i').remove();
							if(d.type == 'success')
							{
								$(".message").append("<div class='alert alert-success'>"+d.message+"</div>").hide().fadeIn(2000);
							}
							if(d.type == 'error')
							{
								$(".message").append("<div class='alert alert-danger'>"+d.message+"</div>").hide().fadeIn(2000);
							}
						},
						error: function(d)
						{
							
						}
	    			});
    			}
    			return false;
    		});
    	}); 
 	});
</script>