<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magento\OfflinePayments\Block\Info\Purchaseorder
 */
?>
<dl class="payment-method purchase order">
    <dt class="title"><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <strong><?php echo $block->escapeHtml(__('Purchase Order Number:')) ?></strong><br />
        <span class="number"><?php echo $block->escapeHtml($block->getInfo()->getPoNumber()) ?></span>
        <br />
        <br />
		<div style="text-align:left;"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bank_details')->toHtml(); ?>
		</div>
    </dd>
</dl>
